# Simple Two - Asset Portfolio in python!

In [53]:
import numpy as np


## Task 1: Represent the economy
 - A0 → vector of prices at t=0
 - A → matrix of payoffs at T (scenarios × assets)


In [52]:
A0 = np.array([[100,100]])
A = np.array([[103,90],[103,130]])

array([[100, 100]])


## Task 2: Portfolio valuation
Implement:
$V_0(\pi) = A_0 \cdot \pi$
$V_T(\pi) = A \pi$

Matrix–vector multiplication requires matching dimensions because a portfolio payoff is a linear combination of asset payoff vectors, with one coefficient per asset.



In [59]:
pi = np.array([[10],[10]])
V0 = A0 @ pi
V1 = A @ pi

In [64]:
print(V0)
print(V1)

[[2000]]
[[1930]
 [2330]]


In [103]:
values = [0, -2, 5, -1]

if any(v > 0 for v in values):
    print('a')

a


### Task 3: Replicating portfolio
Solve:
$A \pi = C_T$

Using `np.linalg.solve`:

Given that our contingent claim in this scenario is a put option with strike price K = 100, so when the state of the market is down (d) , the payoff would be the stirke price minus the down price, and when the market is up, the payoff would be 0 (we would prefer to sell our asset in the market rather that using our put option)


In [69]:
# given that the first row is the down state, we write our contingent claim with two rows , the first for the down and the second 
# for the up state
CT = np.array([[10],[0]])
pi_star = np.linalg.solve(A,CT)
pi_star
# pi star has the portfolio wieghts that replicate the payoffs of the contingent claim
# this only works when assets are linearly independent (one solution)
# market is complete

array([[ 0.31553398],
       [-0.25      ]])

## Task 4: Arbitrage detection
Check if there exists:
$\pi \quad \text{s.t.} \quad V_0(\pi) \le 0,\; V_T(\pi) \ge 0,\; \exists \omega: V_T(\pi) > 0$


In [83]:
from itertools import product

In [87]:
test = [[-10,-1,1,10],[-10,-1,1,10]]
weights = list(product(*test))
weights

[(-10, -10),
 (-10, -1),
 (-10, 1),
 (-10, 10),
 (-1, -10),
 (-1, -1),
 (-1, 1),
 (-1, 10),
 (1, -10),
 (1, -1),
 (1, 1),
 (1, 10),
 (10, -10),
 (10, -1),
 (10, 1),
 (10, 10)]

In [104]:
arbitrage_portfolio = []
for x in range(len(weights)):
    pi_test = np.array([[weights[x][0]],[weights[x][1]]])

    V1 = A @ pi_test

    V0 = A0 @ pi_test

    if V0 <= 0 and V1[0] >= 0 and V1[1] >= 0 and any(x > 0 for x in V1):
        arbitrage_portfolio.append(pi_test)

arbitrage_portfolio
# there is not any arbitrage portfolio in the set of portfolios that we've checked

[]

## 5. Using simplex to check if the inequality exisits:

In [106]:
# first we define our objective vector
c = [0,0]

# then out inequality matrix
A_ub = [
    [100,100],
    [-103,-90],
    [-103,-130]
]

b_ub = [0,0,0]

from scipy.optimize import linprog

res = linprog(c, A_ub = A_ub, b_ub=b_ub, method = "simplex")
res

/var/folders/1f/54wv342x795c_zyzqlgyjjkw0000gn/T/ipykernel_15070/762582400.py:15: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res = linprog(c, A_ub = A_ub, b_ub=b_ub, method = "simplex")


 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 0.0
       x: [ 0.000e+00  0.000e+00]
     nit: 3

In [16]:
all([x for true in range(10)])

True

In [ ]:
numbers = [1, 2, 3]

squared = list(map(lambda x: x**2, numbers))
squared

pi = np.array([[10],[10]])
V0 = A0 @ pi
V1 = A @ pi

[1, 4, 9]

In [2]:
a = [12,3,4]
try:
    a[5]
except IndexError:
    print('xd')

xd


In [8]:
if 0 < 1 <2:
    print('what?')

what?
